### ISSUE TITLE
client_lib.cpp, line 704

### ISSUE THREAD

**Issue by mikkmer** [BillytheButcher/GABB#15]
`return std::wstring(path) + L"\\AppData\\Local\\Growtopia\\save.dat";`

yeah... pretty self explanatory

**Comment by Crandetan** [comment]
wanan have sex?

**Comment by Crandetan** [comment]
> wanan have sex?

just kidding bruv

**Comment by bacontsu** [comment]
bruh lol yea it is indeed save.dat stealer
